# Generated by Django 4.2.11 on 2024-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('photo', models.ImageField(upload_to='my_images')),
                ('doc', models.ImageField(upload_to='doc')),
            ],
        ),
    ]
